# Generated by Django 4.2.24 on 2025-09-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_attivita', models.CharField(max_length=200)),
                ('account_riferimento', models.CharField(blank=True, max_length=200)),
                ('tipologia_cliente', models.CharField(choices=[('AAA', 'AAA'), ('A', 'A'), ('B', 'B')], max_length=3)),
                ('servizio', models.CharField(choices=[('sito_vetrina', 'Sito Vetrina'), ('sito_strutturato', 'Sito Strutturato'), ('ecommerce', 'E-commerce'), ('landing_page', 'Landing Page'), ('blog', 'Blog'), ('mantenimento', 'Mantenimento')], max_length=50)),
                ('data_richiesta', models.DateField(auto_now_add=True)),
                ('fase_processo', models.CharField(blank=True, choices=[('prima_call', 'Prima Call'), ('implementazione', 'Implementazione'), ('presentazione', 'Presentazione'), ('da_mettere_online', 'Da Mettere Online'), ('online', 'Online'), ('gestione_mantenimento', 'Gestione/Mantenimento'), ('stand_by', 'Stand-by'), ('insoluto', 'Insoluto'), ('da_fare', 'Da Fare')], max_length=50)),
                ('seo_stato', models.CharField(blank=True, choices=[('', 'Nessuno'), ('call', 'Call'), ('analisi', 'Analisi'), ('ottimizzazione_testi', 'Ottimizzazione Testi'), ('yoast_seo', 'Yoast SEO'), ('gestione_blog', 'Gestione Blog'), ('gestione_seo', 'Gestione SEO'), ('report', 'Report')], max_length=50)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['scadenza', 'nome_attivita'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('developer', 'Sviluppatore Web'), ('seo', 'SEO Specialist')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro del Team',
                'verbose_name_plural': 'Membri del Team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_completamento', models.DateField(blank=True, null=True)),
                ('servizio', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clients.client')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.teammember')),
            ],
            options={
                'verbose_name': 'Storico Progetto',
                'verbose_name_plural': 'Storico Progetti',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('clienti_attivi', models.IntegerField(default=0)),
                ('clienti_standby', models.IntegerField(default=0)),
                ('clienti_mantenimento', models.IntegerField(default=0)),
                ('data_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot Mensile',
                'verbose_name_plural': 'Snapshot Mensili',
                'ordering': ['-anno', '-mese'],
                'unique_together': {('mese', 'anno')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='operatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='clients.teammember'),
        ),
    ]
