# Generated by Django 4.2.24 on 2025-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fase_processo',
            field=models.CharField(blank=True, choices=[('prima_call', 'Prima Call'), ('implementazione', 'Implementazione'), ('in_revisione', 'In revisione'), ('presentazione', 'Presentazione'), ('da_mettere_online', 'Da Mettere Online'), ('online', 'Online'), ('gestione_mantenimento', 'Gestione/Mantenimento'), ('stand_by', 'Stand-by'), ('insoluto', 'Insoluto'), ('da_fare', 'Da Fare')], max_length=50),
        ),
    ]
