# Generated by Django 4.2.24 on 2025-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_fase_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='servizio',
            field=models.CharField(choices=[('sito_vetrina', 'Sito Vetrina'), ('sito_strutturato', 'Sito Strutturato'), ('ecommerce', 'E-commerce'), ('landing_page', 'Landing Page'), ('app_webapp', 'App/Webapp'), ('blog', 'Blog'), ('mantenimento', 'Mantenimento')], max_length=50),
        ),
    ]
