# Generated by Django 4.2.24 on 2025-10-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_servizio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fase_processo',
            field=models.CharField(blank=True, choices=[('prima_call', 'Prima call'), ('implementazione', 'Implementazione'), ('in_revisione', 'In revisione'), ('presentazione', 'Presentazione'), ('da_mettere_online', 'Da mettere online'), ('online', 'Online'), ('gestione', 'Gestione'), ('mantenimento', 'Mantenimento'), ('stand_by', 'Stand-by'), ('insoluto', 'Insoluto'), ('da_fare', 'Da fare')], max_length=50),
        ),
    ]
