# Generated by Django 4.2.24 on 2025-10-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_fase_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_richiesta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
