# Generated by Django 4.2.24 on 2025-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_data_richiesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-data_richiesta', 'nome_attivita'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clienti'},
        ),
        migrations.AlterField(
            model_name='client',
            name='servizio',
            field=models.CharField(choices=[('sito_vetrina', 'Sito Vetrina'), ('sito_strutturato', 'Sito Strutturato'), ('ecommerce', 'E-commerce'), ('landing_page', 'Landing Page'), ('app_webapp', 'App/Webapp'), ('blog', 'Blog'), ('mantenimento', 'Mantenimento'), ('gestione', 'Gestione')], max_length=50),
        ),
    ]
